context:
  version: "0.0.5"

package:
  name: cdk-cli
  version: ${{ version }}

source:
  url: https://github.com/zachcp/cdk-cli/releases/download/v${{ version }}/cdkcli-${{ version }}.jar
  sha256: dbb6f8c9063b50fc473ae40ec02ce9c715a746a179534825e6c967de91d9b568

build:
  script:
    - if: unix
      then:
        - TGT="$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM"
        - mkdir -p "$TGT"
        - mkdir -p $PREFIX/bin
        - cp $RECIPE_DIR/cdkcli.sh $TGT/cdk-cli
        - ln -s $TGT//cdk-cli $PREFIX/bin
        - cp -p "$SRC_DIR"/*.jar "$TGT"
        - chmod 0755 "${PREFIX}/bin/cdk-cli"

requirements:
  run:
    - openjdk >=17

tests:
  - script:
      - cdk-cli --help

about:
  homepage: https://github.com/zachcp/cdk-cli
  summary: CLI Utilities for the Chemistry Development kit
  description: |-
    CLI Utilities for the Chemistry Development kit
  license: MIT
  repository: https://github.com/zachcp/cdk-cli
