package:
  name: bpy
  version: "4.3.0"

source:
  - if: win64
    then:
      url: "https://files.pythonhosted.org/packages/7f/da/c255b626cab58c69c49f4a65d0410b36aa1086dc63862d1c3de653f0a5a0/bpy-4.3.0-cp311-cp311-win_amd64.whl"
      sha256: 1a7b2c516aa7a95c31fcaae8842addd07fa86c1ce4768e88a34b480d17e2e93a
  - if: linux64
    then:
      url: "https://files.pythonhosted.org/packages/9c/4d/897bf3c247d7c6a4e75397f4c5dd5d201fb147981d2271ac35ac955959ab/bpy-4.3.0-cp311-cp311-manylinux_2_28_x86_64.whl"
      sha256: 1620199392a7e7aab58672aa47c50b3c5b1e4d39d46af5a7f9bbe2af561ea942
  - if: osx and x86_64
    then:
      url: "https://files.pythonhosted.org/packages/81/39/4e763b150ff05412ab25d5eae91da7f0ade474b5d66509b39a67066d35ec/bpy-4.3.0-cp311-cp311-macosx_11_0_x86_64.whl"
      sha256: 490aa94699664a99eee755047485a3ad70470fc6267c55a73459660f52299ade
  - if: osx and arm64
    then:
      url: "https://files.pythonhosted.org/packages/c1/fc/5902fa508a13f4f1669bc2e2cd8f37adf1caeeed0a344f627c0ffc3bdc40/bpy-4.3.0-cp311-cp311-macosx_11_0_arm64.whl"
      sha256: 82c3486e9762e8cfce4bbc1d6752f5625da8515f6b217e02810350627d693897

build:
  number: 0
  script: |
    pip install --no-deps *.whl -v
    python -c "
    with open('$PREFIX/lib/python3.11/site-packages/bpy-4.3.0.dist-info/WHEEL', 'r') as f:
        content = f.read()
    with open('$PREFIX/lib/python3.11/site-packages/bpy-4.3.0.dist-info/WHEEL', 'w') as f:
        f.write(content.replace('cp39', 'cp311'))
    "

requirements:
  host:
    - python =3.11
    - python_abi ==3.11
    - pip
    - wheel
  run:
    - python =3.11
    - python_abi ==3.11
    - cython
    - numpy <2.0
    - requests
    - zstd

tests:
  - python:
      imports:
        - bpy
      pip_check: false

about:
  homepage: https://pypi.org/project/bpy/
  license: GPL-3.0
  summary: Blender as a Python Module
