package:
  name: pypept
  version: "1.0"

source:
  url: https://github.com/Boehringer-Ingelheim/pyPept/archive/refs/tags/Production.zip
  sha256: 0be5c5429b423bae9925247fb536808e69e975acf4e6a17f1516fc0aab4e70c4

build:
  noarch: python
  script:
    - pip install . -v
    - TGT="$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM"
    - mkdir -p "$TGT"
    - mkdir -p $PREFIX/bin
    - cp $RECIPE_DIR/run_pyPept.py $TGT/run_pyPept.py
    - ln -s $TGT/run_pyPept.py $PREFIX/bin
    - chmod 0755 "${PREFIX}/bin/run_pyPept.py"

requirements:
  host:
    - pip
    - python >=3.9
    - rdkit
    - setuptools
    - wheel
  run:
    - biopython >=1.79
    - rdkit
    - pandas

tests:
  - script:
      - run_pyPept --help

about:
  homepage: https://github.com/Boehringer-Ingelheim/pyPept
  summary: Peptides Using the BILN Line Notation
  description: |-
    Peptides Using the BILN Line Notation
  license: MIT
  repository: https://github.com/Boehringer-Ingelheim/pyPept
