context:
  version: 0.1.0

package:
  name: mvs-cli
  version: ${{ version }}

source:
  - git: https://github.com/zachcp/mvs-cli.git
    rev: d16ca69e5ac062a289f0a2b6604295eb7b151879

build:
  script: |
    # Install latest Deno
    if [[ "$target_platform" == "win-64" ]]; then
      # For Windows, use zip download method
      DENO_VERSION="2.1.4"
      curl -fsSL "https://github.com/denoland/deno/releases/download/v${DENO_VERSION}/deno-x86_64-pc-windows-msvc.zip" -o deno.zip
      unzip deno.zip
      mkdir -p "$HOME/.deno/bin"
      mv deno.exe "$HOME/.deno/bin/"
    else
      # For Unix-like systems (Linux and macOS)
      curl -fsSL https://deno.land/install.sh | sh -s -- --no-modify-path
    fi

    # Add Deno to PATH
    export PATH="$HOME/.deno/bin:$PATH"

    # Verify Deno installation
    deno --version

    # Create bin directory
    mkdir -p $PREFIX/bin

    # Compile to standalone executable with all required permissions
    deno compile \
      --allow-read \
      --allow-write \
      --allow-env \
      --allow-net \
      --allow-run \
      --output $PREFIX/bin/mvs \
      main.ts

    # Ensure the binary is executable (Unix-like systems only)
    if [[ "$target_platform" != "win-64" ]]; then
      chmod +x $PREFIX/bin/mvs
    fi
  number: 1

requirements:
  build:
    - curl # For downloading Deno
    - unzip # For Windows Deno installation
  run: []

tests:
  - script:
      - mvs --help
      - mvs --version

about:
  summary: A Deno-backed CLI tool for molecular visualization
  description: |
    MVS CLI is a command-line interface built with Deno for molecular
    visualization and analysis tasks.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/zachcp/mvs-cli
  repository: https://github.com/zachcp/mvs-cli

extra:
  recipe-maintainers:
    - zachcp
